name: Publish on NPM
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
      - run: yarn 
      - run: yarn eslint:ci
      - run: yarn build
      - run: yarn test
      - run: npx codecov
